# Drives the "Sponsor this project" button on the repository page.
# https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [LINDECKER-Charles]
ko_fi: charleslindecker
